# Build stage
FROM node:20-alpine AS builder

# Build arguments for SvelteKit static env vars
ARG PUBLIC_POCKETBASE_URL=http://localhost:8090
ARG PUBLIC_SITE_URL=http://localhost:5173
ARG PUBLIC_COMPANY_NAME="QCS Cargo"
ARG PUBLIC_COMPANY_PHONE="201-249-0929"
ARG PUBLIC_COMPANY_EMAIL="sales@qcs-cargo.com"
ARG PUBLIC_COMPANY_ADDRESS="35 Obrien St, E12 Kearny, NJ 07032"
ARG PUBLIC_STRIPE_KEY=""
ARG PUBLIC_SENTRY_DSN=""
ARG KINDE_ISSUER_URL=""
ARG KINDE_CLIENT_ID=""
ARG KINDE_CLIENT_SECRET=""
ARG KINDE_REDIRECT_URL=""
ARG KINDE_POST_LOGOUT_REDIRECT_URL=""
ARG KINDE_POST_LOGIN_REDIRECT_URL=""

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source
COPY . .

# Set environment variables for build time
ENV PUBLIC_POCKETBASE_URL=$PUBLIC_POCKETBASE_URL
ENV PUBLIC_SITE_URL=$PUBLIC_SITE_URL
ENV PUBLIC_COMPANY_NAME=$PUBLIC_COMPANY_NAME
ENV PUBLIC_COMPANY_PHONE=$PUBLIC_COMPANY_PHONE
ENV PUBLIC_COMPANY_EMAIL=$PUBLIC_COMPANY_EMAIL
ENV PUBLIC_COMPANY_ADDRESS=$PUBLIC_COMPANY_ADDRESS
ENV PUBLIC_STRIPE_KEY=$PUBLIC_STRIPE_KEY
ENV PUBLIC_SENTRY_DSN=$PUBLIC_SENTRY_DSN
ENV KINDE_ISSUER_URL=$KINDE_ISSUER_URL
ENV KINDE_CLIENT_ID=$KINDE_CLIENT_ID
ENV KINDE_CLIENT_SECRET=$KINDE_CLIENT_SECRET
ENV KINDE_REDIRECT_URL=$KINDE_REDIRECT_URL
ENV KINDE_POST_LOGOUT_REDIRECT_URL=$KINDE_POST_LOGOUT_REDIRECT_URL
ENV KINDE_POST_LOGIN_REDIRECT_URL=$KINDE_POST_LOGIN_REDIRECT_URL

# Build application
RUN npm run build

# Production stage
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

# Copy built application
COPY --from=builder /app/build ./build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

ENV HOST=0.0.0.0
ENV PORT=3000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/health || exit 1

CMD ["node", "build"]